apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: checkout-memory-leak
  namespace: default
spec:
  mode: one
  selector:
    labelSelectors:
      app: checkoutservice
  stressors:
    memory:
      workers: 8
      size: '2GB'
  duration: '30m'