from core.state import InvestigationState
from langchain_core.messages import SystemMessage, AIMessage
from langchain_core.prompts import load_prompt
from core.llm_init import llm
from yaml import safe_load

# initial investigation function -- called at the very beginning
def initial_investigation(state: InvestigationState) -> InvestigationState:
    """
    For very first iterative investigation step, since we do not have any initial hypothese,
    we need to generate one by observing the alert message only. Once the hypotheses is generated,
    we need to call a suitable tool or tools as per our requirement. 
    """
    try:
        initial_prompt = [SystemMessage(load_prompt("../prompts/Investigation_Begin.yaml"))]
        initial_response = llm.invoke(initial_prompt.format(alert= state["incident_description"]))
        yaml_response = safe_load(initial_response.content)
        state["hypotheses"] = yaml_response["hypotheses"]
        state["next_node"] = int(yaml_response["next_step"])
        return state
    except Exception as error:
        raise RuntimeError(
            f'Initial RCA investigation failed:\nReason: {error}.'
        )
# iterative investigation function -- making conclusions from given logs/evidence
def iterative_investigation(state: InvestigationState) -> InvestigationState:
    """
    When we have our initail hypotheses, we need to verify it with the evidence we have collected so 
    far with the various tools we have called. Once the hypotheses are updated, we must think about the 
    next tool call (may not call next tool if confidence is high), along with the confidence score for 
    the solution.
    """
    try:
        initial_prompt = [SystemMessage(load_prompt("../prompts/Iterative_Investigation.yaml"))]
        initail_response = llm.invoke(
            initial_prompt.format(hypotheses=state["hypotheses"],
            evidence=state["evidence"])
        )
        yaml_response = safe_load(initail_response)
        state["hypotheses"] = yaml_response["hypotheses"]
        state["next_node"] = int(yaml_response["next_step"])
        state["confidence"] = float(yaml_response["confidence"])
        return state
    except Exception as error:
        raise RuntimeError(
            f'Iterative Investigation failure:\nReason: {error}.\n'
        )
# supervisor node function
def supervisor_function(state: InvestigationState) -> InvestigationState:
    """
    You are a supervisor RCA agent, which will be trigerred by alert manager and you will receive
    the alert. You have to use the tools and identify which tools to call, make/update hypotheses.
    Based on the evidence you have collected.
    Args:
        alert: generated by alert manager of prometheus 
    """
    steps = len(state["investigation_steps"])
    next_step = state["next_node"]
    if steps == 0:
        #initial investigation
        return initial_investigation(state)
    elif next_step != 0:
        #tools need to be called
        return state
    else:
        #tools are called need to reiterate on the evidence collected
        return iterative_investigation(state)

